(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(symbol-overlay racket-mode org-ref org-cliplink evil-matchit ein polymode doom-modeline direnv package-lint helm lispy lsp-mode alert js2-mode zoutline yasnippet-snippets yapfify yaml-mode xterm-color ws-butler writeroom-mode winum which-key wgrep websocket web-mode web-beautify volatile-highlights vi-tilde-fringe uuidgen use-package toc-org test-simple tagedit symon string-inflection spaceline-all-the-icons smex smeargle slime-company slim-mode shrink-path shell-pop scss-mode sass-mode rmsbolt restart-emacs request rainbow-delimiters pytest pyenv-mode py-isort pug-mode prettier-js popwin pippel pipenv pip-requirements persp-mode pdf-tools pcre2el password-generator paradox orgit org-projectile org-present org-pomodoro org-mime org-download org-bullets org-brain open-junk-file ob-restclient ob-ipython ob-http neotree nameless multi-term move-text magit-svn magit-gitflow lsp-ui lsp-treemacs lsp-python-ms lorem-ipsum log4e livid-mode live-py-mode lispyville link-hint leuven-theme keyfreq key-chord json-navigator js2-refactor js-doc jinja2-mode ivy-yasnippet ivy-xref ivy-purpose ivy-hydra indent-guide importmagic impatient-mode hungry-delete hl-todo highlight-parentheses highlight-numbers highlight-indentation helm-make helm-lsp helm-core helm-bibtex google-translate golden-ratio godoctor go-tag go-rename go-impl go-guru go-gen-test go-fill-struct go-eldoc gnuplot gntp gitignore-templates gitignore-mode github-search github-clone gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link git-gutter-fringe git-gutter-fringe+ gist ggtags fzf fuzzy forge font-lock+ flycheck-pos-tip flycheck-package flycheck-gometalinter flx-ido fill-column-indicator fancy-battery eyebrowse evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-textobj-line evil-org evil-numbers evil-nerd-commenter evil-mc evil-magit evil-lisp-state evil-lion evil-indent-plus evil-iedit-state evil-goggles evil-exchange evil-escape evil-embrace evil-ediff evil-cleverparens evil-args evil-anzu eval-sexp-fu eshell-z eshell-prompt-extras esh-help emmet-mode elisp-slime-nav editorconfig dumb-jump dotenv-mode dockerfile-mode docker diminish diff-hl devdocs define-word dash-at-point dap-mode cython-mode csv-mode counsel-projectile counsel-gtags counsel-dash counsel-css company-web company-tern company-statistics company-restclient company-quickhelp company-lsp company-go company-ansible company-anaconda common-lisp-snippets column-enforce-mode clean-aindent-mode centered-cursor-mode browse-at-remote bm blacken base16-theme auto-yasnippet auto-highlight-symbol auto-compile ansible-doc ansible aggressive-indent ace-link ac-ispell)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
